# Assignment 9: Bayesian Analysis

### Conditional Probability 

Q.1. Let's say there are about 8.6 million people living in New-York and about 56 % of them speak Spanish. Let's also assume there are about 7.5 billion people on earth.

If I randomly pick someone living on Earth (an Earthian?), what are the chances that this person is a Spanish speaking New-Yorker?

Q.2 Explain in few terms what is Naive Bayes. What is it considered Naive?

Q.3 Let's suppose we have a Deck of Cards (52 cards). We pick a card at random. What is the probability of the card we picked being a king, given that it is a face card. 

# Q1 Answer 

In [12]:
P_spanish_nyc = 0.56 * 8.6 * 10**6 / (7.5 * 10**9)
print(P_spanish_nyc)

0.0006421333333333333


Naive Bayes

 Naïve Bayes is a simplified Bayes Network, where the outcome variable depends on other variables, which do not depend on each other

In [13]:
P_king = 1 / 3
print(P_king)

0.3333333333333333


In [14]:
import pandas as pd

data = pd.read_csv('shingles.csv')
print(data.info())
data.head()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1841 entries, 0 to 1840
Data columns (total 6 columns):
Rash                       1841 non-null object
SwollenLymphNode           1841 non-null object
Chills                     1841 non-null object
PolymeraseChainReaction    1841 non-null object
VZVAntibodyTest            1841 non-null object
Blisters                   1841 non-null object
dtypes: object(6)
memory usage: 86.4+ KB
None


Rash SwollenLymphNode Chills PolymeraseChainReaction VZVAntibodyTest  \
0   no               no     no                      no             pos   
1  yes               no     no                      no             neg   
2   no               no     no                      no             neg   
3   no               no     no                      no             neg   
4   no               no     no                      no             neg   

  Blisters  
0       no  
1       no  
2       no  
3       no  
4       no

In [15]:
for column in data:
    print(data[column].unique())

['no' 'yes']
['no' 'yes']
['no' 'yes']
['no' 'yes']
['pos' 'neg' 'yes']
['no' 'yes' 'neg' 'pos' 'po']


In [16]:
data.replace(['po', 'yes', 'pos'], 1, inplace=True)
data.replace(['no', 'neg'], 0, inplace=True)

In [17]:
for column in data:
    print(data[column].unique())

[0 1]
[0 1]
[0 1]
[0 1]
[1 0]
[0 1]


Q.4. Does this data contain any missing values?

In [18]:
missing_values = data.isna().sum().sum()
print('There is {} missing values'.format(missing_values))

There is 0 missing values


In [19]:
print('the best marker for shingle is VZVAntibodyTestne hence it would be considered as the result for our model')

the best marker for shingle is VZVAntibodyTestne hence it would be considered as the result for our model


Q.5. Split the data into 70/30 train test

In [20]:
from sklearn.model_selection import train_test_split

X = data.loc[:, data.columns != 'VZVAntibodyTest'].values
y = data.loc[:, data.columns == 'VZVAntibodyTest'].values
y = [a[0] for a in y]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

Q.6. Train a Gaussian Naive Bayes model, a Multinomial Naive Bayes and a Bernoulli Naive Bayes on the dataset. Compute the accuracy for each. Explain your results. 

In [21]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import mean_squared_error, confusion_matrix
import numpy as np


models = [[GaussianNB(), 'Gaussian Naive Bayes'], [MultinomialNB(), 'Multinomial Naive Bayes'], 
          [BernoulliNB(), 'Bernoulli Naive Bayes']]

results = []
for model, name in models:
    model.fit(X_train, y_train)
    y_predict = model.predict(X_test)
    RMSE = np.sqrt(mean_squared_error(y_test, y_predict))
    Conf = confusion_matrix(y_test, y_predict)
    prob_pos = model.predict_proba(X_test)
    score = model.score(X_train, y_train)
    results.append([y_predict, name ,RMSE, Conf, score, prob_pos,])


for result in results:
    
    print('Model {}\n RMSE\n {}\n\n Confusion Matrix\n {}\n\n Score\n {}\n'.format(*result[1:-1]))
  
  


Model Gaussian Naive Bayes
 RMSE
 0.6249773956129332

 Confusion Matrix
 [[254  77]
 [139  83]]

 Score
 0.609472049689441

Model Multinomial Naive Bayes
 RMSE
 0.6132945449904222

 Confusion Matrix
 [[288  43]
 [165  57]]

 Score
 0.6133540372670807

Model Bernoulli Naive Bayes
 RMSE
 0.6088556841509863

 Confusion Matrix
 [[276  55]
 [150  72]]

 Score
 0.6242236024844721



In [22]:
Naive Bayes produces the best results

SyntaxError: invalid syntax (<ipython-input-22-ddc90a6e56ce>, line 1)

## Inference in Bayesian networks

Q.7. Imagine you are at party on Sunday and have an exam on Monday.  If you drink
too much alcolhol at the birthday party, you most likely have problems concentrating the next day, which
would reduce the probability that you pass the exam.  Another consequence of the reduced concentration
might be increased stress with your roommate.

Consider the following random variables that can assume the values "true" or "false":
A:  drinking too much alcolhol on Sunday;
B:  Dairy allergy strikes;
C:  reduced concentration on Monday;
D:  you pass the exam;
E:  stress with your roommates.

a) Draw the corresponding Bayesian network.

b) Search for conditional dependencies and independencies.

In [ ]:
# https://graphviz.readthedocs.io/en/stable/manual.html
from graphviz import Digraph
from IPython.display import SVG
from IPython.display import display

dot = Digraph(comment='Bayesian Networks - Student Life')
dot.node('A', 'Drinking too much')
dot.node('B', 'Dairy allergy strikes')
dot.node('C', 'reduced concentration on Monday')
dot.node('D', 'you pass the exam')
dot.node('E', 'stress with your roommates')

dot.edges(['AC', 'BC', 'CD', 'CE', 'BE', 'BD', ])

display(SVG(dot.pipe(format='svg')))



There are multpile dependencies. Drinking can generate allergy 
the exam can stress you against your roommates
